export const Posts = {
	FETCH_REQUEST: "POSTS/FETCH_REQUEST",
	FETCH_SUCCESS: "POSTS/FETCH_SUCCERS",
	FETCH_ERROR: "POSTS/FETCH_ERROR",
	FETCH_POST: "POSTS/FETCH_POST",
	ADD_POST: "POSTS/ADD_POST",
	DELETE_POST: "POSTS/DELETE_POST",
};
